apiVersion: v1
entries:
  velero-backup-operations:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-02-08T18:21:47.695325726Z"
    description: A Helm chart for triggering Velero Backups
    digest: 3dc7656d7462c70d1749d2dd7217741de57cbdc0230ff07de49076d179dd9674
    name: velero-backup-operations
    type: application
    urls:
    - https://kwant-dbg.github.io/helm-charts/charts/velero-backup-operations-1.4.0.tgz
    version: 1.4.0
generated: "2026-02-08T18:21:47.694632664Z"
